server.port=9090
# Configuration de connexion à MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/jee26
spring.datasource.username=bdio
spring.datasource.password=bdio
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration de JPA/Hibernate (pour créer les tables automatiquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mySecretKeyMySecretKeyMySecretKey12345

