server.port=9090
# Configuration de connexion � MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/jee26
spring.datasource.username=root
spring.datasource.password=hamid2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration de JPA/Hibernate (pour cr�er les tables automatiquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#jwt.secret=mySecretKeyMySecretKeyMySecretKey12345

# JWT Configuration
jwt.secret=mySuperSecretKeyForJWTThatIsLongEnoughToBeSecure1234567890
# Optional: if your JwtUtil also uses an expiration placeholder
jwt.expiration=86400000
